# Generated by Django 4.2.4 on 2025-09-01 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurers', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado'), ('COMPLETED', 'Concluído')], db_index=True, default='PENDING', max_length=20)),
                ('client_name', models.CharField(max_length=255)),
                ('client_document', models.CharField(help_text='CNPJ/CPF', max_length=20)),
                ('client_address', models.TextField(blank=True)),
                ('client_contact', models.CharField(blank=True, max_length=100)),
                ('cargo_type', models.CharField(max_length=100)),
                ('cargo_value', models.DecimalField(decimal_places=2, help_text='Valor médio por embarque', max_digits=12)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('monthly_revenue', models.DecimalField(decimal_places=2, help_text='Faturamento mensal estimado', max_digits=15)),
                ('general_lmg', models.DecimalField(decimal_places=2, help_text='LMG Geral', max_digits=12)),
                ('container_lmg', models.DecimalField(blank=True, decimal_places=2, help_text='LMG Container', max_digits=12, null=True)),
                ('rj_operation_lmg', models.DecimalField(blank=True, decimal_places=2, help_text='LMG Operação RJ', max_digits=12, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rctr_c_rate', models.DecimalField(decimal_places=4, help_text='Taxa RCTR-C (%)', max_digits=6)),
                ('rc_dc_rate', models.DecimalField(decimal_places=4, help_text='Taxa RC-DC (%)', max_digits=6)),
                ('rctr_c_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rc_dc_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rctr_c_franchise', models.CharField(default='10% com mínimo de R$ 1.000,00', max_length=100)),
                ('rc_dc_franchise', models.CharField(default='10% com mínimo de R$ 1.000,00', max_length=100)),
                ('premium_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observations', models.TextField(blank=True)),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurers.insurer')),
                ('quote_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='quotes.quoterequest')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovado'), ('REJECTING', 'Rejeitando'), ('REJECTED', 'Rejeitado'), ('PROCESSING', 'Processando'), ('COMPLETED', 'Concluído')], db_index=True, default='PENDING', max_length=20)),
                ('valid_until', models.DateField()),
                ('rctr_c_rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('rc_dc_rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('rctr_c_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rc_dc_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_premium', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pdf_file', models.CharField(blank=True, max_length=255, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('quote_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.quoterequest')),
                ('quote_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.quoteresult')),
            ],
        ),
    ]
