# Generated by Django 4.2.4 on 2025-08-29 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado'), ('PROCESSING', 'Processando'), ('COMPLETED', 'Concluído')], db_index=True, default='PENDING', max_length=20)),
                ('client_name', models.CharField(db_index=True, max_length=255)),
                ('valid_until', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cargo_type', models.CharField(max_length=100)),
                ('cargo_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurers.insurer')),
                ('quote_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quotes.quoterequest')),
            ],
        ),
    ]
