# Generated by Django 4.2.4 on 2025-09-02 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovado'), ('REJEITANDO', 'Rejeitando'), ('REJEITADA', 'Rejeitado'), ('PROCESSANDO', 'Processando'), ('CONCLUIDA', 'Concluído')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovado'), ('REJEITADA', 'Rejeitado'), ('CONCLUIDA', 'Concluído')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
