# Generated by Django 4.2.4 on 2025-08-29 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='client_name',
        ),
        migrations.AddField(
            model_name='proposal',
            name='pdf_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='quote_request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quotes.quoterequest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='rc_dc_limit',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='rc_dc_rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='rctr_c_limit',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='rctr_c_rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='total_premium',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='client_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='client_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='client_document',
            field=models.CharField(default=1, help_text='CNPJ/CPF', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='client_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='container_lmg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='LMG Container', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='general_lmg',
            field=models.DecimalField(decimal_places=2, default=1, help_text='LMG Geral', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='monthly_revenue',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Faturamento mensal estimado', max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='rj_operation_lmg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='LMG Operação RJ', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='quoteresult',
            name='observations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quoteresult',
            name='rc_dc_franchise',
            field=models.CharField(default='10% com mínimo de R$ 1.000,00', max_length=100),
        ),
        migrations.AddField(
            model_name='quoteresult',
            name='rc_dc_limit',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quoteresult',
            name='rc_dc_rate',
            field=models.DecimalField(decimal_places=4, default=1, help_text='Taxa RC-DC (%)', max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quoteresult',
            name='rctr_c_franchise',
            field=models.CharField(default='10% com mínimo de R$ 1.000,00', max_length=100),
        ),
        migrations.AddField(
            model_name='quoteresult',
            name='rctr_c_limit',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quoteresult',
            name='rctr_c_rate',
            field=models.DecimalField(decimal_places=4, default=1, help_text='Taxa RCTR-C (%)', max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proposal',
            name='quote_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.quoteresult'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='cargo_value',
            field=models.DecimalField(decimal_places=2, help_text='Valor médio por embarque', max_digits=12),
        ),
        migrations.AlterField(
            model_name='quoteresult',
            name='premium_value',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='quoteresult',
            name='quote_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='quotes.quoterequest'),
        ),
    ]
