# Generated by Django 4.2.4 on 2025-10-07 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_riskcity_specialcondition_systemparameter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='is_current_version',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='quotes.quoterequest'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(max_length=255)),
                ('item_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('item_quantity', models.IntegerField(default=1)),
                ('quote_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotes.quoterequest')),
            ],
        ),
    ]
