# docker-compose.yml (Versão final corrigida)

# CORREÇÃO: Mudamos a definição da âncora de uma lista para um mapa (chave: valor).
# Removemos os traços (-) e trocamos o igual (=) por dois pontos (:).
x-django-env: &django-env
  POSTGRES_DB: shamah_db
  POSTGRES_USER: shamah_user
  POSTGRES_PASSWORD: shamah_password
  POSTGRES_HOST: db
  DJANGO_SETTINGS_MODULE: config.settings.development
  REDIS_URL: redis://redis:6379/0

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      # Este formato está correto (é um mapa por padrão quando não há traços).
      POSTGRES_DB: shamah_db
      POSTGRES_USER: shamah_user
      POSTGRES_PASSWORD: shamah_password

  redis:
    image: redis:6.2-alpine

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      # A mesclagem agora vai funcionar, pois a âncora é um mapa.
      <<: *django-env
    depends_on:
      - db
      - redis

  celery_worker:
    build: ./backend
    command: celery -A config worker -l info
    volumes:
      - ./backend:/app
    environment:
      <<: *django-env
    depends_on:
      - redis
      - db

  celery_beat:
    build: ./backend
    command: celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./backend:/app
    environment:
      <<: *django-env
    depends_on:
      - redis
      - db

  frontend:
    build:
      context: ./frontend/shamah-frontend
      target: development
    command: pnpm run dev --host
    volumes:
      - ./frontend/shamah-frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data: