# Generated by Django 4.2.4 on 2025-09-01 23:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('minimum_premium', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('max_rctr_c_limit', models.DecimalField(decimal_places=2, default=500000.0, max_digits=12)),
                ('max_rc_dc_limit', models.DecimalField(decimal_places=2, default=300000.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='MerchandiseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('risk_level', models.CharField(choices=[('LOW', 'Baixo'), ('MODERATE', 'Moderado'), ('HIGH', 'Alto'), ('EXTREME', 'Extremo')], default='MODERATE', max_length=10)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='InsurerBusinessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rctr_c_rate', models.DecimalField(decimal_places=4, default=1, help_text='Taxa RCTR-C (%)', max_digits=6)),
                ('rc_dc_rate', models.DecimalField(decimal_places=4, default=1, help_text='Taxa RC-DC (%)', max_digits=6)),
                ('rate', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('high_risk_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplicador para rotas de alto risco', max_digits=4)),
                ('volume_discount_threshold', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Faturamento mínimo para desconto por volume', max_digits=15, null=True)),
                ('volume_discount_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Desconto por volume (%)', max_digits=4)),
                ('franchise_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=4)),
                ('minimum_franchise', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('is_excluded', models.BooleanField(default=False, help_text='Mercadoria excluída por esta seguradora')),
                ('observations', models.TextField(blank=True)),
                ('valid_from', models.DateField(default=django.utils.timezone.now)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurers.insurer')),
                ('merchandise_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurers.merchandisetype')),
            ],
            options={
                'unique_together': {('insurer', 'merchandise_type')},
            },
        ),
    ]
