# Generated by Django 4.2.4 on 2025-08-29 20:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insurers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurer',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='insurer',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='insurer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='insurer',
            name='max_rc_dc_limit',
            field=models.DecimalField(decimal_places=2, default=300000.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='insurer',
            name='max_rctr_c_limit',
            field=models.DecimalField(decimal_places=2, default=500000.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='insurer',
            name='minimum_premium',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='insurerbusinessrule',
            name='franchise_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='insurerbusinessrule',
            name='high_risk_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplicador para rotas de alto risco', max_digits=4),
        ),
        migrations.AddField(
            model_name='insurerbusinessrule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='insurerbusinessrule',
            name='is_excluded',
            field=models.BooleanField(default=False, help_text='Mercadoria excluída por esta seguradora'),
        ),
        migrations.AddField(
            model_name='insurerbusinessrule',
            name='minimum_franchise',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='insurerbusinessrule',
            name='observations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='insurerbusinessrule',
            name='rc_dc_rate',
            field=models.DecimalField(decimal_places=4, default=1, help_text='Taxa RC-DC (%)', max_digits=6),
        ),
        migrations.AddField(
            model_name='insurerbusinessrule',
            name='rctr_c_rate',
            field=models.DecimalField(decimal_places=4, default=1, help_text='Taxa RCTR-C (%)', max_digits=6),
        ),
        migrations.AddField(
            model_name='insurerbusinessrule',
            name='valid_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='insurerbusinessrule',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insurerbusinessrule',
            name='volume_discount_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Desconto por volume (%)', max_digits=4),
        ),
        migrations.AddField(
            model_name='insurerbusinessrule',
            name='volume_discount_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Faturamento mínimo para desconto por volume', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='merchandisetype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='merchandisetype',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'Baixo'), ('MODERATE', 'Moderado'), ('HIGH', 'Alto'), ('EXTREME', 'Extremo')], default='MODERATE', max_length=10),
        ),
        migrations.AlterField(
            model_name='insurerbusinessrule',
            name='rate',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
        ),
    ]
